import { Injectable } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import {config} from './APIConfigs';

@Injectable({
  providedIn: 'root'
})

export class ItemApiCallsService {

  //Constructors
  constructor(private http:HttpClient) { }

  //View saved items call

  //Get all items call 
  getItemsAPICall() {
    return this.http.get('https://exceedinternal.azurewebsites.net/api/User');
  }
  
  //Get items by ID call::For postdetailsPage%
  getItemsByIDCall(id:number){
    const url = `${'https://exceedinternal.azurewebsites.net/api'}/Items/${id}`;
    return this.http.get(url);
  }

  //Post saved items API Call::For founditemsPage,lostitemsPage%
  postSavedItemsAPICall(id:any){
    const url='https://exceedinternal.azurewebsites.net/api/Items/CreateSavedPost';
    return this.http.post(url,id);
  }

  //Post likes of any items::For lostitemsPage,founditemsPage%
  postLikedItemsAPICall(id:any){
    const url='https://exceedinternal.azurewebsites.net/api/Items/CreateLikedPost';
    return this.http.post(url,id);
  }

  //Remove from my saved posts API Call::For ostitemsPage,founditemsPage%
  removeSavedPostAPICall(itemId:number){
    const url=`${'https://exceedinternal.azurewebsites.net/api/Items/RemoveSavedPost/'}${itemId}`;
    return this.http.delete(url);
  }

  //Get all saved posts API Call::For mysavedpostsPage%
  getAllSavedPostsAPICall(){
    return this.http.get('https://exceedinternal.azurewebsites.net/api/Items/GetAllSavedPost');
  }

  //Get lost items call::For lositemsPage% 
  getLostItemsAPICall(){
    return this.http.get('https://exceedinternal.azurewebsites.net/api/Items/GetLostItems');
  }

  //Get found items call::For founditemsPage% 
  getFoundItemsAPICall(){
    return this.http.get('https://exceedinternal.azurewebsites.net/api/Items/GetFoundItems');
  }

  //Post item by ID call
  postUserAPICall(data:any){
    return this.http.post('https://exceedinternal.azurewebsites.net/api/Items', data);
  }

  //Get an items tags generated by the AI for that post::PostDetailsPage%
  getItemtags(itemId:number){
    const url = `${'https://exceedinternal.azurewebsites.net/api/Tag/get-tags/'}${itemId}`;
    return this.http.get<any>(url);
  }

  //Get an items matches made by AI
  getItemsMatches(itemId:number){
    const url = `${'https://exceedinternal.azurewebsites.net/api/Items/'}${itemId}`;
    return this.http.get<any>(url);
  }
}
