import { Injectable } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import {config} from './APIConfigs';

@Injectable({
  providedIn: 'root'
})

export class ItemApiCallsService {

  //Constructors
  constructor(private http:HttpClient) { }

  //Get all items call 
  getItemsAPICall() {
    return this.http.get('https://exceedinternal.azurewebsites.net/api/User');
  }
  
  //Get items by ID call
  getItemsByIDCall(id:number){
    const url = `${'https://exceedinternal.azurewebsites.net/api'}/Items/${id}`;
    return this.http.get(url);
  }

  //Get lost items call 
  getLostItemsAPICall(){
    return this.http.get('https://exceedinternal.azurewebsites.net/api/Items/GetLostItems');
  }

  //Get found items call 
  getFoundItemsAPICall(){
    return this.http.get('https://exceedinternal.azurewebsites.net/api/Items/GetFoundItems');
  }

  //Get item by ID call
  getItemsByIdAPICall(userId:string) {
    const url = `${config.testApi_URL}/users/${userId}`;
    return this.http.get(url);
  }

  //Post item by ID call
  postUserAPICall(data:any){
    return this.http.post('https://exceedinternal.azurewebsites.net/api/Items', data);
  }

  //Update ietm data by ID call
  updateUserAPICall(userId:string, updatedUserData:any) {
    const url = `${config.testApi_URL}/users/${userId}`;
    return this.http.put(url, updatedUserData);
  }

  //Get an items tags generated by the AI for that post::PostDeatilsPage
  getItemtags(itemId:number){
    const url = `${'https://exceedinternal.azurewebsites.net/api/Tag/get-tags/'}${itemId}`;
    return this.http.get<any>(url);
  }

  //Get user items
  getUserItems() {
    return this.http.get<any>('https://exceedinternal.azurewebsites.net/api/Items/GetUserItems');
  }
}
